
@SchoolManagement_HostAddress = http://localhost:5221

GET {{SchoolManagement_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{SchoolManagement_HostAddress}}/api/Student
Content-Type: application/json

{
  "name": "Zaid Ahmad",
  "birthDate": "2002-05-15",
  "classroomId": 1, 
  "subjectId": 1
}
###
GET {{SchoolManagement_HostAddress}}/api/Classroom
Accept: application/json

###
DELETE {{SchoolManagement_HostAddress}}/api/Student/8
###
PUT {{SchoolManagement_HostAddress}}/api/Student/11
Accept: application/json
Content-Type: application/json

{
  "id": 11,
  "name": "Zaid",
  "birthDate": "2004-03-20",
  "classroomId": 1, 
  "subjectId": 2
}

### 
POST {{SchoolManagement_HostAddress}}/api/Student/list
Content-Type: application/json

### 
POST https://localhost:7264/api/Auth/login
Content-Type: application/json

{
  "email": "admin@school.com",
  "password": "123"
}


###
GET https://localhost:7264/api/Classroom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3ODk5NTc5NiwiaXNzIjoiU2Nob29sTWFuYWdlbWVudCIsImF1ZCI6IlNjaG9vbE1hbmFnZW1lbnRVc2VycyJ9.SAlEaHOgKj-710yAjP64K1Y8Kap2POotvOviG8YgDu0


###
GET {{SchoolManagement_HostAddress}}/api/Classroom
Accept: application/json